/**
 * Availability of the built-in design tools (P2.4).
 *
 * `folio_generate_image` is registered only when the asking session is a design
 * session AND this machine has a complete, enabled image connection. Both
 * halves matter: the tool writes generated bytes into the session workdir, and a
 * coding session's workdir is the user's own project repository. The decision
 * belongs to the daemon, which owns the per-machine Flock row and the session
 * metadata; the built-in MCP server asks for it over the same machine-local
 * control socket it already uses for `session/get-active-invocation-context`,
 * rather than opening storage of its own (which would cost a second writer on
 * the machine's SQLite store for a one-row read, and would make the answer
 * depend on the MCP process's own view of a document the daemon is the
 * authority for).
 *
 * The credential travels with that answer and only with that answer: the socket
 * is owner-only, on the same machine, and the MCP server is the daemon's own
 * child running as the same user. It never reaches an MCP server config, an
 * environment variable, a header, or a log line — see the note on the RPC
 * result schema.
 *
 * Absence is the default and every failure resolves to it: a daemon that cannot
 * be reached is not a daemon that said yes, and a session the daemon cannot
 * recognize as a design session is not one. A missing tool is honest, while a
 * registered tool that always errors would teach the agent to stop trying.
 */

import {
  ImageConnectionRpcResultSchema,
  type ImageConnectionSettings,
  type SessionId,
} from '@lody/shared';
import { makeLocalControlClientAuto } from '@lody/shared/node/local-ipc';
import { Effect } from 'effect';

/** How long the gate lookup may take before it is treated as "no capability". */
export const DESIGN_GATE_TIMEOUT_MS = 10_000;

/**
 * What the built-in MCP server needs to know about design capability.
 *
 * A snapshot taken when the server is built, and refreshed before each paid
 * call: the MCP server is constructed per turn on the HTTP transport and once
 * per session on stdio, so a settings change reaches the tool without a restart
 * on the first path and no later than the next session on the second.
 */
export type McpDesignGate = {
  /**
   * `null` unless the asking session is a design session and the machine has a
   * complete, enabled connection; the daemon decides both and folds them into
   * the same answer, so no caller can register the tool on half the condition.
   */
  imageConnection: ImageConnectionSettings | null;
};

export const EMPTY_DESIGN_GATE: McpDesignGate = { imageConnection: null };

export type DesignGateContext = {
  machineId: string;
  workspaceId: string;
  /** The asking session; sent as `ownerSessionId` so the daemon can apply the design-session rule. */
  sessionId: SessionId;
  localControlSocketPath: string | undefined;
};

const errorMessage = (error: unknown): string =>
  error instanceof Error ? error.message : String(error);

/**
 * Turn one daemon answer into a gate — the single place that decides what
 * counts as capability.
 *
 * `ready` already folds in the design-session rule (the daemon applies it, and
 * only the daemon can), so this is deliberately a pure reading of the answer:
 * an unexpected shape, a non-design session, or a connection that is absent,
 * switched off, or keyless all become the same empty gate.
 */
export function designGateFromRpcResult(result: unknown): McpDesignGate {
  const parsed = ImageConnectionRpcResultSchema.safeParse(result);
  if (!parsed.success || parsed.data.type !== 'design/image-connection') {
    return EMPTY_DESIGN_GATE;
  }
  const { connection, ready, credential } = parsed.data;
  if (!ready || connection === null || credential === null) {
    return EMPTY_DESIGN_GATE;
  }
  return {
    imageConnection: {
      v: 1,
      enabled: connection.enabled,
      baseUrl: connection.baseUrl,
      model: connection.model,
      apiKey: credential.apiKey,
      updatedAt: connection.updatedAt,
    },
  };
}

/**
 * Ask the daemon whether image capability exists for this session, and for the
 * connection when it does. Never throws: every failure is a gate that says "not
 * available".
 *
 * `ownerSessionId` is how the daemon applies the design-session half of the
 * rule: the request carries the asking session, and the answer folds session
 * kind and connection readiness into one `ready` bit and one credential. The
 * MCP server therefore never judges session kind itself — it could not, and a
 * second judgment would be a second thing to keep in sync.
 */
export async function resolveDesignGate(
  ctx: DesignGateContext,
  logger?: { debug(message: string): void }
): Promise<McpDesignGate> {
  if (!ctx.localControlSocketPath) {
    logger?.debug('design gate: no local control socket; image tool stays unregistered');
    return EMPTY_DESIGN_GATE;
  }
  try {
    const result = await Effect.runPromise(
      makeLocalControlClientAuto({ socketPath: ctx.localControlSocketPath })
        .machineRpc(
          {
            method: 'design/image-connection',
            machineId: ctx.machineId,
            workspaceId: ctx.workspaceId,
            ownerSessionId: ctx.sessionId,
            params: {},
          },
          { timeoutMs: DESIGN_GATE_TIMEOUT_MS }
        )
        .pipe(
          Effect.catchTag('IpcTimeoutError', (error) =>
            Effect.fail(
              new Error(
                `local control timed out after ${DESIGN_GATE_TIMEOUT_MS}ms (${error.message})`
              )
            )
          ),
          Effect.catchTag('IpcProtocolError', (error) =>
            Effect.fail(new Error(error.message, { cause: error }))
          )
        )
    );
    if (!result.ok) {
      logger?.debug(`design gate: daemon refused the lookup: ${result.error}`);
      return EMPTY_DESIGN_GATE;
    }
    const gate = designGateFromRpcResult(result.result);
    if (gate.imageConnection === null) {
      logger?.debug(
        'design gate: session is not an eligible design session, or the image connection is absent, disabled, or incomplete'
      );
    }
    return gate;
  } catch (error) {
    logger?.debug(`design gate: lookup failed: ${errorMessage(error)}`);
    return EMPTY_DESIGN_GATE;
  }
}
